lane :ExecutionTest do

  scan(
    project: "IOSFrameworkProject.xcodeproj"
  )
  xcov

end

lane :DeployementMaster do

  if git_branch() == "master"
    version = get_version_number()
    set_github_release(
      repository_name: "PicoPark/IOSFrameworkProject",
      name: "v#{version}",
      tag_name: "v#{version}",
      api_token: ENV["GITHUB_TOKEN"],
      description: change_log_since_last_tag || "Release commit",
      commitish: "master"
    )
    pod_push()
  end
end
